### PR TITLE
update gs to gs4

### PR DESCRIPTION
**Pull request by baobabprince**
make compatible with googlesheets4 package

### CODE REVIEW

**Comment by daattali** [comment]
Fixes #41

**Comment by baobabprince** [comment]
Thats break the package it's better to revert it. I will try again more deeply and hopefully update soon

**Comment by daattali** [comment]
Could you please send a PR for the revert?
---
Dean Attali
President & CEO
AttaliTech Ltd
https://AttaliTech.com <https://attalitech.com>

**Comment by baobabprince** [comment]
I hope I did it well. my first time to PR.

**Pull request merged**
